### ISSUE TITLE
Add option to use as a GH Action

### ISSUE THREAD

**Issue by Secrus** [davidism/gha-update#2]
The project seems great. It would be nice to be able to use it as an action directly, instead of setting it up manually, especially when managing multiple repositories.

**Comment by davidism** [comment]
The motivation for this script is to remove scheduled PRs. It's still possible to run this directly and then use something like https://github.com/stefanzweifel/git-auto-commit-action to commit and push any changes. There are actions for creating PRs instead of direct pushes as well. I don't think it's worth me learning how to implement and maintain an action just to re-implement those.
